;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        markdown-cycle
        markdown-enter-key
        slime-compile-defun
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        helm-M-x
        markdown-outdent-or-delete
        mouse-set-region
        sp-backward-delete-char
        swiper
        ))
