;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        slime-compile-defun
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        sp-backward-delete-char
        ))
